#pragma once
#include "system_detection.h"
#include "system_error.h"
#include "system_headers.h"
#include "system_manager.h"
#include "system_traits.h"
#include "system_traits_macos.h"
#include "system_type.h"
#include "system_window.h"
